// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdvancedQuery(arg1, arg2) {
  return window['go']['main']['App']['AdvancedQuery'](arg1, arg2);
}

export function CompactDatabase(arg1, arg2) {
  return window['go']['main']['App']['CompactDatabase'](arg1, arg2);
}

export function CountDocuments(arg1, arg2) {
  return window['go']['main']['App']['CountDocuments'](arg1, arg2);
}

export function CreateBackup(arg1, arg2) {
  return window['go']['main']['App']['CreateBackup'](arg1, arg2);
}

export function CreateCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2, arg3);
}

export function CreateDatabase(arg1, arg2) {
  return window['go']['main']['App']['CreateDatabase'](arg1, arg2);
}

export function CreateIndex(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateIndex'](arg1, arg2, arg3, arg4);
}

export function DeleteCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteCollection'](arg1, arg2, arg3);
}

export function DeleteDatabase(arg1, arg2) {
  return window['go']['main']['App']['DeleteDatabase'](arg1, arg2);
}

export function DeleteDocument(arg1, arg2) {
  return window['go']['main']['App']['DeleteDocument'](arg1, arg2);
}

export function ExportData(arg1, arg2) {
  return window['go']['main']['App']['ExportData'](arg1, arg2);
}

export function GetCollections(arg1, arg2) {
  return window['go']['main']['App']['GetCollections'](arg1, arg2);
}

export function GetDatabaseStats(arg1, arg2) {
  return window['go']['main']['App']['GetDatabaseStats'](arg1, arg2);
}

export function GetDetailedDatabaseStats(arg1, arg2) {
  return window['go']['main']['App']['GetDetailedDatabaseStats'](arg1, arg2);
}

export function GetSupportedFormats(arg1) {
  return window['go']['main']['App']['GetSupportedFormats'](arg1);
}

export function ImportData(arg1, arg2) {
  return window['go']['main']['App']['ImportData'](arg1, arg2);
}

export function ImportDataFromContent(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ImportDataFromContent'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function InsertDocument(arg1, arg2) {
  return window['go']['main']['App']['InsertDocument'](arg1, arg2);
}

export function ListBackups(arg1) {
  return window['go']['main']['App']['ListBackups'](arg1);
}

export function ListDatabases(arg1) {
  return window['go']['main']['App']['ListDatabases'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function QueryDocuments(arg1, arg2) {
  return window['go']['main']['App']['QueryDocuments'](arg1, arg2);
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function UpdateDocument(arg1, arg2) {
  return window['go']['main']['App']['UpdateDocument'](arg1, arg2);
}

export function ValidateSession(arg1) {
  return window['go']['main']['App']['ValidateSession'](arg1);
}
