// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {engine} from '../models';
import {auth} from '../models';

export function AdvancedQuery(arg1:string,arg2:service.AdvancedQueryRequest):Promise<Array<service.DocumentResponse>>;

export function CompactDatabase(arg1:string,arg2:string):Promise<void>;

export function CountDocuments(arg1:string,arg2:service.AdvancedQueryRequest):Promise<number>;

export function CreateBackup(arg1:string,arg2:service.BackupRequest):Promise<engine.BackupInfo>;

export function CreateCollection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateDatabase(arg1:string,arg2:string):Promise<void>;

export function CreateIndex(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteCollection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteDatabase(arg1:string,arg2:string):Promise<void>;

export function DeleteDocument(arg1:string,arg2:service.DeleteRequest):Promise<void>;

export function ExportData(arg1:string,arg2:service.ExportRequest):Promise<void>;

export function GetCollections(arg1:string,arg2:string):Promise<Array<service.CollectionInfo>>;

export function GetDatabaseStats(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetDetailedDatabaseStats(arg1:string,arg2:string):Promise<engine.DatabaseStats>;

export function GetSupportedFormats(arg1:string):Promise<Array<string>>;

export function ImportData(arg1:string,arg2:service.ImportRequest):Promise<engine.ImportResult>;

export function ImportDataFromContent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<engine.ImportResult>;

export function InsertDocument(arg1:string,arg2:service.InsertRequest):Promise<void>;

export function ListBackups(arg1:string):Promise<Array<engine.BackupInfo>>;

export function ListDatabases(arg1:string):Promise<Array<service.DatabaseInfo>>;

export function Login(arg1:auth.LoginRequest):Promise<auth.LoginResponse>;

export function Logout(arg1:string):Promise<void>;

export function QueryDocuments(arg1:string,arg2:service.QueryRequest):Promise<Array<service.DocumentResponse>>;

export function Register(arg1:auth.RegisterRequest):Promise<auth.LoginResponse>;

export function RestoreBackup(arg1:string,arg2:service.RestoreRequest):Promise<void>;

export function UpdateDocument(arg1:string,arg2:service.UpdateRequest):Promise<void>;

export function ValidateSession(arg1:string):Promise<auth.Session>;
